"""Domain model for a saved search query.

This is the single source of truth for what a saved query *is*. The API
layer reuses this model for both request bodies (where appropriate) and
response bodies, avoiding duplicate definitions.
"""

from datetime import datetime

from pydantic import BaseModel


class SavedQuery(BaseModel):
    """One saved search query — a what/where pair the agent will run."""

    query_id: str               # short UUID generated by the store
    what: str                   # job type, e.g. "data scientist"
    where: str                  # location, e.g. "canada", "toronto", "remote"
    enabled: bool = True        # disable without deleting
    created_at: datetime
